#!/bin/bash
# notify of local overrides of nags/reports

basedir=/usr/local/collaboration

for confdir in ${basedir}/dispatch ${basedir}/nag ${basedir}/report ; do
    if [[ -d ${confdir}/local ]]; then
	for local in $(ls ${confdir}/local); do
	    echo "${confdir}/local/${local}" >> $tmpdir/$modname
	    if [[ -f ${confdir}/${local} ]]; then
		diff -u ${confdir}/${local} ${confdir}/local/${local} >> $tmpdir/$modname
	    else
		diff -u /dev/null ${confdir}/local/${local} >> $tmpdir/$modname
	    fi
	    echo >> $tmpdir/$modname
	done
    fi
done
if [[ -s $tmpdir/$modname ]]; then
    echo "local script overrides:" >> $tmpfile
    cat $tmpdir/$modname >> $tmpfile
    echo >> $tmpfile
fi
