#!/bin/bash
# check for runaway processes

cpudiscard=$(echo ${cpuignores[@]} |sed 's/ /|/g')
cpucheck ${maxcpu:-10} ${cputime:-100} |egrep -vw "${cpudiscard:-foobar}" > $tmpdir/$modname
if [ -s $tmpdir/$modname ]; then
    echo "processes over maxcpu:" >> $tmpfile
    cat $tmpdir/$modname >> $tmpfile
    echo >> $tmpfile
fi

