#!/bin/bash

rootdir=/magic/deprov

for uniqname in $(cat $1) ; do
    dirname=${rootdir}/$uniqname
    if [[ ! -e $dirname/verified ]]; then
        echo "$uniqname not downloaded"
        continue
    fi
    (
        flock -n 9 || exit 1
        startts=$(date -Iseconds)
        if [[ ! -e $dirname/uploaded ]]; then
            echo "Uploading files for $uniqname"
            gdm -c /etc/odm.google.yaml filetree $dirname/files upload --upload-user $uniqname --upload-path "Migrated from OneDrive 2019" -v 2> $dirname/stderr.${startts}.upload
            retval=$?
            if [[ $retval -eq 0 ]]; then
                echo "Successfully uploaded $uniqname"
                touch $dirname/uploaded
            else
                echo "Failed to upload $uniqname"
                exit
            fi
        fi
    ) 9>>$dirname/lockfile
    if [[ $? -ne 0 ]]; then
        echo "$uniqname already locked"
    fi
done
