#!/bin/bash

rootdir=${rootdir:-/magic/migration}

for dirname in $rootdir/* ; do
    uniqname=$(basename $dirname)
    if [[ -e $dirname/uploaded ]]; then
        echo "$uniqname,100"
        continue
    fi

    if [[ ! -e $dirname/verified || ! -e $dirname/split ]]; then
        echo "$uniqname,0"
        continue
    fi

    total=0
    uploaded=0
    for splitlist in $dirname/metadata-split-*.json ; do
        (( total++ ))
        [[ -e ${splitlist}.uploaded ]] && (( uploaded++ ))
    done

    if [[ $uploaded -eq $total ]]; then
        touch $dirname/uploaded
    fi
    echo -n "$uniqname,"
    dc -e "2 k $uploaded $total / 100 * p"
done
