#!/bin/bash

rootdir=${rootdir:-/magic/migration}

for uniqname in $(cat $1) ; do
    dirname=${rootdir}/$uniqname
    [[ -e $dirname ]] || mkdir -p $dirname
    if [[ -e $dirname/uploaded ]]; then
        echo "$uniqname already uploaded and verified"
        continue
    fi
    (
        flock -n 9 || exit 1
        startts=$(date -Iseconds)
        if [[ ! -e $dirname/verified ]]; then
            if [[ ! -s $dirname/metadata.json ]]; then
                echo "Fetching metadata for $uniqname"
                odm -c /etc/odm.5d55.yaml user $uniqname list-items > $dirname/metadata.json
                [[ -s $dirname/metadata.json ]] || exit
            fi
            try=0
            retval=1
            until [[ $retval -eq 0 ]] || [[ $try -gt 3 ]]; do
                echo "Downloading files for $uniqname (try $try)"
                odm -c /etc/odm.5d55.yaml list $dirname/metadata.json download --filetree $dirname/files -v 2> $dirname/stderr.${startts}.download.$try
                retval=$?
                if [[ $try -eq 0 ]] && [[ $retval -ne 0 ]]; then
                    # The API might have lied about the hashes
                    echo "Re-fetching metadata for $uniqname"
                    mv $dirname/metadata.json $dirname/metadata.old
                    odm -c /etc/odm.5d55.yaml user $uniqname list-items > $dirname/metadata.json
                    [[ -s $dirname/metadata.json ]] || exit
                fi
                (( try++ ))
            done
            if [[ $retval -eq 0 ]]; then
                echo "Successfully verified $uniqname download"
                touch $dirname/verified
            else
                echo "Failed to download $uniqname"
                exit
            fi
        fi

        if [[ -d $dirname/files ]]; then
            echo "Uploading files for $uniqname"
            odm -c /etc/odm.umich.yaml list $dirname/metadata.json upload --filetree $dirname/files --upload-user $uniqname --domain-map 5d55e1824c5a44e68bc2.onmicrosoft.com:umich.edu,ms365archive.it.umich.edu:umich.edu -v 2> $dirname/stderr.${startts}.upload
            if [[ $? -eq 0 ]]; then
                echo "Successfully uploaded $uniqname"
                touch $dirname/uploaded
            fi
            tail -1 $dirname/stderr.${startts}.upload
        else
            echo "Nothing to upload for $uniqname"
            touch $dirname/uploaded
        fi
    ) 9>>$dirname/lockfile
    if [[ $? -ne 0 ]]; then
        echo "$uniqname already locked"
    fi
done
