#!/bin/bash

rootdir=${rootdir:-/magic/migration}

for uniqname in $(cat $1) ; do
    dirname=${rootdir}/$uniqname
    [[ -e $dirname ]] || mkdir -p $dirname
    if [[ -e $dirname/uploaded ]]; then
        echo "$uniqname already uploaded and verified"
        continue
    fi

    startts=$(date -Iseconds)

    if [[ ! -e $dirname/verified ]]; then
        (
            flock -n 9 || exit 1
            if [[ ! -s $dirname/metadata.json ]]; then
                echo "Fetching metadata for $uniqname"
                odm -c /etc/odm.5d55.yaml user $uniqname list-items > $dirname/metadata.json
                [[ -s $dirname/metadata.json ]] || exit
            fi
            try=0
            retval=1
            until [[ $retval -eq 0 ]] || [[ $try -gt 3 ]]; do
                echo "Downloading files for $uniqname (try $try)"
                odm -c /etc/odm.5d55.yaml list $dirname/metadata.json download --filetree $dirname/files -v 2> $dirname/stderr.${startts}.download.$try
                retval=$?
                (( try++ ))
            done
            if [[ $retval -eq 0 ]]; then
                echo "Successfully verified $uniqname download"
                touch $dirname/verified
            else
                echo "Failed to download $uniqname"
                exit
            fi
        ) 9>>$dirname/lockfile
    fi

    [[ -s $dirname/metadata.json ]] || continue
    [[ -e $dirname/verified ]] || continue
    [[ -d $dirname/files ]] || continue

    if [[ ! -e $dirname/split ]]; then
        (
            flock -n 9 || exit 1
            odm-splitlist $dirname/metadata.json $dirname/metadata-split-
            [[ $? -eq 0 ]] && touch $dirname/split
        ) 9>>$dirname/lockfile
    fi

    [[ -e $dirname/split ]] || continue

    notdone=0
    for splitlist in $dirname/metadata-split-*.json ; do
        [[ -e ${splitlist}.uploaded ]] && continue
        listnum=${splitlist//[^0-9]/}
        (
            flock -n 9 || exit 1
            echo "Uploading file list $listnum for $uniqname"
            logf=$dirname/stderr.${startts}.${listnum}.upload
            odm -c /etc/odm.umich.yaml list $splitlist upload --filetree $dirname/files --upload-user $uniqname --domain-map 5d55e1824c5a44e68bc2.onmicrosoft.com:umich.edu,ms365archive.it.umich.edu:umich.edu -v 2> $logf
            retval=$?
            if [[ $retval -eq 0 ]]; then
                echo "Successfully uploaded file list $listnum for $uniqname"
                touch  ${splitlist}.uploaded
            fi
            tail -1 $logf
            exit $retval
        ) 9>>${splitlist}.lockfile
        [[ $? -eq 0 ]] || (( notdone++ ))
    done

    if [[ $notdone -eq 0 ]]; then
        echo "Finished uploading $uniqname"
        touch $dirname/uploaded
    fi
done
