#!/bin/bash

rootdir=/magic/migration

for dirname in $rootdir/* ; do
    uniqname=$(basename $dirname)
    [[ -e $dirname/zerolen ]] && continue
    (
        flock -n 9 || exit 1
        if [[ ! -e $dirname/uploaded ]]; then
            echo "Not necessary to fix $uniqname"
            touch $dirname/zerolen
            exit
        fi

        startts=$(date -Iseconds)
        if [[ ! -s $dirname/new-metadata.json ]]; then
            echo "Fetching metadata for $uniqname"
            odm -c /etc/odm.umich.yaml user $uniqname list-items --skip-permissions > $dirname/new-metadata.json
            [[ -s $dirname/new-metadata.json ]] || exit
        fi

        echo "Fixing $uniqname"
        odm-zerolen $dirname/new-metadata.json > $dirname/new-metadata-zl.json
        odm -c /etc/odm.umich.yaml list $dirname/new-metadata-zl.json upload --upload-user $uniqname --filetree $dirname/files -v 2> $dirname/stderr.${startts}.zerolen
        retval=$?
        tail -1 $dirname/stderr.${startts}.zerolen
        if [[ $retval -eq 0 ]]; then
            echo "Successfully fixed $uniqname"
            touch $dirname/zerolen
        else
            echo "Failed to fix $uniqname"
            exit
        fi
    ) 9>>$dirname/lockfile
    if [[ $? -ne 0 ]]; then
        echo "$uniqname already locked"
    fi
done
