#!/usr/bin/env python

import json
import sys

with open(sys.argv[1]) as f:
    metadata = json.load(f)

nonzero = []
for item_id in metadata['items']:
    item = metadata['items'][item_id]
    if 'file' not in item:
        continue
    if item['size'] == 0:
        item['odm_zero'] = True
        while 'id' in item['parentReference']:
            item =  metadata['items'][item['parentReference']['id']]
            item['odm_zero'] = True

for item_id in metadata['items']:
    if 'odm_zero' not in metadata['items'][item_id]:
        nonzero.append(item_id)

for item_id in nonzero:
    metadata['items'].pop(item_id)

print(json.dumps(metadata, indent = 2))
