# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [[ $SUDO_USER ]]; then
    . ~/ansible-aws/env-setup.sh
fi

export SYSTEMD_PAGER=
export VAULT_ADDR='http://127.0.0.1:8200'

