- tags:
    - okta
  block:
    - name: Install pam_okta
      ansible.builtin.dnf:
        name: pam_okta
        state: latest

    - name: Configure pam_okta
      ansible.builtin.template:
        src: pam_okta.toml.j2
        dest: /etc/security/pam_okta.toml
        owner: root
        group: root
        mode: "0600"

    - name: Configure PAM for sshd
      ansible.builtin.copy:
        src: sshd.pam
        dest: /etc/pam.d/sshd
        owner: root
        group: root
        mode: "0644"
