#!/bin/bash

hacking_dir=$(readlink -fn $(dirname "$BASH_SOURCE"))

$hacking_dir/build-ami

if [[ $? -eq 0 ]]; then
    for i in $(ansible localhost --playbook-dir $hacking_dir/ansible -m debug -a 'msg={{ aws_region_layout[aws_status][aws_region] | list }}' | grep '        ' | tr -d '", ' | tr '-' '_'); do
        [[ $i = 'master' ]] && continue
        [[ $i = 'syslog' ]] && continue
        [[ $i = 'builder' ]] && continue
        [[ $i = 'dev' ]] && continue
        $hacking_dir/build-ami $i &
        sleep 1m
    done
fi

wait
