#!/usr/local/venv/system/bin/python3

import argparse
import datetime
import smtplib
import subprocess

from email.mime.text import MIMEText


sender = 'its.core.applications@umich.edu'
dest = 'blackops.root@umich.edu'
relay_host = 'vdc-relay.mail.umich.edu'

classes = frozenset({
    'mx',
    'authn-relay',
    'authz-relay',
    'authz-static',
    'vdc-relay',
    'egress',
    'relay-egress',
})

parser = argparse.ArgumentParser()
parser.add_argument('--daily-csv', action='store_true')
args = parser.parse_args()

errors = ''

script_args = []
if args.daily_csv:
    script_args.extend(['--csv', '--period=1d'])

for cls in classes:
    report = subprocess.run(
        ['/usr/local/bin/simta-report', *script_args, cls],
        capture_output=True,
        text=True,
    )

    if report.returncode != 0:
        errors += f'Errors from {cls}:'
        errors += report.stderr;
        continue

    if args.daily_csv:
        with open(f'/var/log/simta-reports/{cls}.csv'), 'w') as f:
            f.write(report.stdout)
    else:
        msg = MIMEText(report.stdout)
        msg['Subject'] = f'{cls} simta report {(datetime.date.today() - datetime.timedelta(days=7)).isoformat()} to {(datetime.date.today() - datetime.timedelta(days=1)).isoformat()}'
        msg['From'] = sender
        msg['To'] = dest
        smtplib.SMTP(relay_host).sendmail(sender, dest, msg.as_string())

if errors:
    msg = MIMEText(errors)
    msg['Subject'] = f'simta report errors {datetime.date.today().isoformat()}'
    msg['From'] = sender
    msg['To'] = dest
    smtplib.SMTP(relay_host).sendmail(sender, dest, msg.as_string())
