#!/usr/local/venv/sensu/bin/python3

import json
import sys


event = json.load(sys.stdin)

tags = [
    {
        'name': 'sensu_check',
        'value': event['check']['metadata']['name'],
    },
]

for label in event['entity']['metadata'].get('labels', {}).items():
    tags.append({
        'name': label[0],
        'value': label[1],
    })

points = []
for key in ['duration', 'occurrences', 'status']:
    if key in event['check']:
        points.append(
            {
                'name': 'sensu_event.{}'.format(key),
                'value': event['check'][key],
                'tags': tags,
                'timestamp': event['timestamp'],
            }
        )

event['metrics'] = {
    'points': points,
}

print(json.dumps(event))
