#!/bin/dash

if check_dfile; then
    spamout=$(rspamc --json --timeout=20 --ip="$SIMTA_REMOTE_IP" --from="<$SIMTA_SMTP_MAIL_FROM>" --helo="$SIMTA_SMTP_HELO" --hostname="$SIMTA_REMOTE_HOSTNAME" $SIMTA_DFILE 2>/dev/null)

    # Use jq to format the JSON into the bits we want
    spamres=$(printf '%s' $spamout | jq -r '@text "\(.action) score=\(.score)"')
    if [ $? -ne 0 ]; then
        log "80_rspamd: bad return: $(echo $spamout | tr -d '\n')"
    fi
    spamsymbols=$(printf '%s' $spamout | jq -j '.symbols[] | del(.description) | flatten | @text')
    spamaction=${spamres% score=*}

    log "80_rspamd: $spamres symbols={$spamsymbols}"
    case "$spamaction" in
    reject)
        echo "mscan.reject.rspamd:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
        filter_exit $MESSAGE_REJECT
        ;;
    greylist)
        # PENALTYBOX_PASS is from 70_pb
        if [ $PENALTYBOX_PASS -eq 1 ] ; then
            logmsg=$($penaltybox_bin $penaltybox_args "rspamd")
            pbret=$?
            if [ x"$logmsg" != x ]; then
                log "80_rspamd: $logmsg"
            fi
            if [ $pbret -eq $MESSAGE_TEMPFAIL ]; then
                echo "mscan.tempfail.rspamd:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
                filter_exit $MESSAGE_TEMPFAIL
            fi
            PENALTYBOX_PASS=0
        fi
        ;;
    esac
fi
