#!/bin/dash

if [ "x$SIMTA_ACL_RESULT" = 'xtrust' ]; then
    log "15_trust: trusted host, skipping further tests"
    echo "mscan.accept.trust:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
    filter_exit ${MESSAGE_ACCEPT}
fi
