#!/bin/dash
# deny recipients, for *outbound* delivery only

allow=0
deny=/etc/mail/deny.to

if [ -s $deny ] && check_tfile; then
    to=$(sed -n -e '/^R/s/^R//p' $SIMTA_TFILE | fgrep -i -o -wf $deny)
    if [ $? -eq 0 ]; then
        log "21_to: $deny matched $to"
	filter_exit $(( ${MESSAGE_ACCEPT} + ${MESSAGE_DELETE} ))
    fi
fi

