#!/bin/dash
# deny based on UBL filter

if [ $SIMTA_AUTH_ID ] ; then
    ubl=$(simrbl -l ubl.dnsbl -t $SIMTA_AUTH_ID)
    if [ $? -eq 1 ]; then
	log "21_ubl: $ubl"
        echo "mscan.reject.ubl:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
	filter_exit ${MESSAGE_REJECT}
    fi
fi
