#!/bin/dash
# deny based on UBL filter

if check_env \$SIMTA_AUTH_ID ; then
    ubl=$(simrbl -l ubl.dnsbl -t $SIMTA_AUTH_ID)
    if [ $? -eq 1 ]; then
	log "21_ubl: $SIMTA_AUTH_ID on ${ubl##* }"
        echo "mscan.reject.ubl:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
	filter_exit ${MESSAGE_REJECT}
    fi
fi
