#!/bin/dash
# deny based on ns record of domain in envelope from

allow=0
deny=/etc/mail/deny.nsrecord

if [ -s $deny ] && check_env \$SIMTA_SMTP_MAIL_FROM; then
    domain=${SIMTA_SMTP_MAIL_FROM#*@}
    for ns in $(dig +short $domain NS); do
	nsrecord=$(echo $ns | fgrep -o -f $deny)
	allow=$(( $allow + $? ))
    done
    if [ $allow -eq 0 ]; then
	log "30_nsrecord: $deny matched $nsrecord"
	filter_exit ${MESSAGE_REJECT}
    fi
fi

