#!/bin/dash

acceptlist=/etc/mail/recipient.trust
rejectlist=/etc/mail/recipient.deny

if [ $SIMTA_TFILE ]; then
    if [ -s $acceptlist ]; then
        match=$(jq -r .recipients[] $SIMTA_TFILE | fgrep -ixf $acceptlist 2>/dev/null)
        ret=$?
        if [ $ret -eq 0 ]; then
            log "35_recipient: $acceptlist matched $match"
            echo "mscan.accept.recipient:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
            filter_exit ${MESSAGE_ACCEPT}
        fi
    fi
    if [ -s $rejectlist ]; then
        match=$(jq -r .recipients[] $SIMTA_TFILE | fgrep -ixf $rejectlist 2>/dev/null)
        ret=$?
        if [ $ret -eq 0 ]; then
            log "35_recipient: $rejectlist matched $match"
            echo "mscan.reject.recipient:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
            filter_exit ${MESSAGE_REJECT}
        fi
    fi
fi
