#!/bin/dash
# deny based on string in message

deny=/etc/mail/deny.string

if [ -s $deny ] && check_dfile; then
    str=$(fgrep -o -f $deny $SIMTA_DFILE)
    if [ $? -eq 0 ]; then
        log "40_string: $deny matched $str"
        echo "mscan.tempfail.string:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
	filter_exit ${MESSAGE_TEMPFAIL}
    fi
fi

