- tags:
    - clamav
  block:
    - name: Install freshclam
      ansible.builtin.dnf:
        name: clamav-update
        state: latest

    - name: Correct permissions on signature directory
      # https://bugzilla.redhat.com/show_bug.cgi?id=2499753
      ansible.builtin.file:
        dest: /var/lib/clamav
        state: directory
        owner: clamupdate
        group: clamupdate
        mode: "0755"

    - name: Configure freshclam
      ansible.builtin.template:
        dest: /etc/freshclam.conf
        src: freshclam.conf.j2
        owner: root
        group: root
        mode: "0644"

    - name: Run freshclam
      command: freshclam
      register: result
      changed_when: result.rc == 0
      failed_when: result.rc > 1

    - name: Schedule freshclam
      cron:
        name: freshclam
        minute: "*/5"
        job: "freshclam --quiet && jq -n -r '{ check: { metadata: { name: \"clamav-freshclam\" }, ttl: 86400, status: 0, output: \"successfully synced signatures\" }}' | curl -X POST -H 'Content-Type: application/json' -d @- http://127.0.0.1:3031/events &>/dev/null"
