#!/bin/bash

base=/var/spool/simta
critical=4
warn=1
age=120

while getopts a:c:q:w: opt; do
    case $opt in
    a)  age=$OPTARG
        ;;
    c)  critical=$OPTARG
        ;;
    w)  warn=$OPTARG
        ;;
    q)  queue=${base}/$OPTARG
        ;;
    esac
done

if [[ ! -d $queue ]]; then
    echo "No queue directory: $queue"
    exit 2
fi

qcount=$(find $queue -ignore_readdir_race -type f -name 'E*' -mmin +$age 2>/dev/null | wc -l)
echo "$qcount messages older than $age minutes in $queue"
if [[ $qcount -gt $critical ]]; then
    exit 2
elif [[ $qcount -gt $warn ]]; then
    exit 1
fi

exit 0
