#!/bin/bash

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

redis_host=pink.us-east-2.x.mail.umich.edu
workdir=/var/cache/seshet

while getopts d:H:w: opt; do
    case $opt in
    d)  datastore_args=$OPTARG
        ;;
    H)  redis_host=$OPTARG
        ;;
    esac
done

(
    flock -n 9 || exit 1
    [[ -e $workdir ]] || mkdir $workdir
    cd $workdir
    grep -Fh 'failed to authenticate' /var/log/remote/*.authn-relay.*/mail | awk '{print $5, $7}' | tr -d '][' | sort -u | awk '{print $1}' | uniq -c | awk '{ if ($1 > 1) print $2 }' | seshet-record -H $redis_host
    seshet-retrieve -H $redis_host >| seshet
    if [[ $? -eq 0 ]]; then
        datastore-upload $datastore_args seshet dnsl/umich/seshet
    fi
)9>>/run/seshet.lock

exit 0
