#!/usr/bin/env python

import argparse

import netaddr

from redis import RedisCluster


parser = argparse.ArgumentParser()
parser.add_argument('-H', '--host', default='localhost')
parser.add_argument('-P', '--port', default='6379')
parser.add_argument('-t', '--threshold', type=int, default=15)
args = parser.parse_args()

red = RedisCluster(
    host=args.host,
    port=args.port,
    decode_responses=True,
)

ips = netaddr.IPSet()
for subkey in red.scan_iter(match='seshet:subnet:*', count=1000):
    subres = red.hgetall(subkey)

    if len(subres) > args.threshold:
        ips.add(subkey.replace('seshet:subnet:', ''))
        continue

    for key in subres.keys():
        ips.add(key)

print('# IPs automatically banned from relay services')
print(':127.0.0.3:Blocked due to suspicious activity')
print('127.0.0.2   test')
print()

for cidr in ips.iter_cidrs():
    if cidr.size == 1:
        print(cidr.ip)
    else:
        print(cidr)
