#!/bin/bash

redis_host=pink.us-east-2.x.mail.umich.edu

while getopts H: opt; do
    case $opt in
    H)  redis_host=$OPTARG
        ;;
    esac
done

(
    flock -n 9 || exit 1
    grep -Fh 'failed to authenticate' /var/log/remote/*.authn-relay.*/mail | awk '{print $5, $7}' | tr -d '][' | sort -u | awk '{print $1}' | uniq -c | awk '{ if ($1 > 1) print $2 }' | seshet-record -H $redis_host
)9>>/run/seshet.lock

exit 0
