#!/usr/bin/env python

import argparse
import sys

from datetime import date

import maxminddb
import netaddr
from redis import RedisCluster


def record_ip(ip_str, verbose):
    ip = netaddr.IPAddress(ip_str)
    subnet = netaddr.IPNetwork(ip)
    if ip.version == 6:
        subnet.prefixlen = 48
    else:
        subnet.prefixlen = 24

    subkey = 'seshet:subnet:{0}/{1}'.format(str(subnet[0]), subnet.prefixlen)
    if verbose:
        print('Recording {0} to {1}'.format(str(ip), subkey))
    red.hset(subkey, str(ip), today.strftime('%F'))
    red.expire(subkey, 60 * 60 * 24 * 30 * 6)   # approximately six months
    if verbose:
        print(red.hgetall(subkey))


today = date.today()

parser = argparse.ArgumentParser()
parser.add_argument('-H', '--host', default='localhost')
parser.add_argument('-P', '--port', default='6379')
parser.add_argument('-v', '--verbose', action='store_true')
args = parser.parse_args()

red = RedisCluster(
    host=args.host,
    port=args.port,
    decode_responses=True,
)

mmdb = maxminddb.open_database('/usr/share/GeoIP/GeoLite2-Country.mmdb')

for ip in sys.stdin:
    ip = ip.rstrip()
    cc = mmdb.get(ip).get('country', {}).get('iso_code', 'US')
    if cc != 'US':
        record_ip(ip, args.verbose)
