#!/bin/bash

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

redis_host=pink.us-east-2.x.mail.umich.edu
workdir=/var/cache/seshet

while getopts H:w: opt; do
    case $opt in
    H)  redis_host=$OPTARG
        ;;
    esac
done

(
    flock -n 9 || exit 1
    [[ -e $workdir ]] || mkdir $workdir
    cd $workdir
    if [[ ! -s simta.conf ]]; then
        cat >simta.conf <<EOF
receive dmarc {
    public_suffix_file = /etc/mail/public_suffix_list.dat;
}
EOF
    fi

    startts=$(date +%s%N)

    yesterday=$(date -d yesterday +%Y%m%d)
    zstdcat /var/log/remote/*.mx.*/mail-${yesterday}.zst | grep -E "Receive .*: env <.*>: From <.+@.+>: Accepted" | sed -e 's/.*@//; s/>:.*//' | tr A-Z a-z | sort -u | xargs simorgdomain -f simta.conf | sort -u | seshet-record-domain -H $redis_host -d $(date -d yesterday +%F)

    duration=$(( $(date +%s%N) - startts ))

    jq -n -r \
        --arg status 0 \
        --arg duration $(( duration / 1000000000 )).$(( duration % 1000000000 /1000000 )) \
        --arg msg "$msg" \
        '{ check: { metadata: { name: "seshet-domains", annotations: { "fatigue_check/occurrences": "2" }}, ttl: 93600, duration: $duration | tonumber, status: $status | tonumber, output: $msg }}' | curl -X POST -H 'Content-Type: application/json' -d @- http://127.0.0.1:3031/events

)9>>/run/seshet-domains.lock

exit 0
