#!/usr/bin/env python

import argparse

import netaddr

from datetime import date, timedelta

from redis import RedisCluster


parser = argparse.ArgumentParser()
parser.add_argument('-H', '--host', default='localhost')
parser.add_argument('-P', '--port', default='6379')
parser.add_argument('-t', '--threshold', type=int, default=1)
args = parser.parse_args()

red = RedisCluster(
    host=args.host,
    port=args.port,
    decode_responses=True,
)

threshold = (date.today() - timedelta(days=args.threshold)).strftime('%F')

for key in red.scan_iter(match='seshet:known_domain:*', count=1000):
    added = red.hget(key, 'added')
    if added <= threshold:
        print(key.replace('seshet:known_domain:', ''))
