#!/bin/bash

seal=$(curl -k -s https://127.0.0.1:8200/v1/sys/seal-status 2>&1)

if [[ $? -ne 0 ]]; then
    echo "curl error:"
    echo "$seal"
    retval=2
elif [[ $(echo "$seal" | jq .sealed) != 'false' ]]; then
    echo "Vault is sealed"
    echo "$seal" | jq
    retval=2
else
    echo "Vault is unsealed"
    retval=0
fi

exit $retval
