#!/bin/bash

while getopts c: opt; do
    case $opt in
    c)  cluster=$OPTARG
        ;;
    esac
done

retval=0

ips=$(dig +short $cluster)
if [[ -z $ips ]]; then
    echo "Unable to resolve $cluster"
    exit 3
fi

for ip in $ips; do
    if [[ $(redis-cli -h $ip PING 2>&1) = 'PONG' ]]; then
        state=$(redis-cli --cluster check ${ip}:6379 2>&1)
        [[ $state =~ '[OK] All nodes agree about slots configuration.' ]] || retval=1
        [[ $state =~ '[OK] All 16384 slots covered.' ]] || retval=2

        echo "$state"

        exit $retval
    fi
done

echo "No PONG from any hosts in $cluster"
exit 3

