#!/usr/local/venv/sensu/bin/python3

import argparse
import os
import smtplib
import sys


parser = argparse.ArgumentParser()
parser.add_argument('-u', '--username', required=True)
parser.add_argument('-H', '--host', default='127.0.0.1')
parser.add_argument('-P', '--port', default=25)
parser.add_argument('-t', '--tls', action='store_true')
args = parser.parse_args()

try:
    dest = '{}:{}'.format(args.host, args.port)
    if args.tls:
        server = smtplib.SMTP_SSL(dest)
    else:
        server = smtplib.SMTP(dest)
        server.starttls()
    server.login(args.username, os.environ.get('SMTP_PASSWORD'))
    server.quit()
    print('Authentication Successful')
    sys.exit(0)
except (smtplib.SMTPAuthenticationError, smtplib.SMTPNotSupportedError) as e:
    print('Authentication Failed')
    print(e)
    sys.exit(2)
except (smtplib.socket.error, smtplib.socket.gaierror) as e:
    print(e)
    sys.exit(1)
except Exception as e:
    print(e)
    sys.exit(3)
