#!/usr/local/venv/sensu/bin/python3

import boto3
import requests


reject_tags = [
    'Name',
    'CustomDNSName',
]

region = requests.get('http://169.254.169.254/latest/meta-data/placement/availability-zone').text[:-1]

client = boto3.client('ec2', region_name=region)
pager = client.get_paginator('describe_instances')
metrics = {}

filters = [{'Name': 'instance-state-name', 'Values': ['running']}]
for res in pager.paginate(Filters=filters).build_full_result()['Reservations']:
    for instance in res['Instances']:
        cooked = []
        for tag in instance.get('Tags', []):
            if tag['Key'] not in reject_tags and tag['Value'] != 'no':
                if tag['Value'] == 'yes':
                    cooked.append('flag={}'.format(tag['Key']))
                else:
                    cooked.append('{}={}'.format(tag['Key'], tag['Value'].replace(' ', '_')))
        cooked.append('az={}'.format(instance['Placement']['AvailabilityZone']))
        cooked.sort()
        influx_tags = ','.join(cooked)
        if influx_tags in metrics:
            metrics[influx_tags] += 1
        else:
            metrics[influx_tags] = 1

for m in metrics:
    print('ec2,{} instance_count={}'.format(m, metrics[m]))
