#!/bin/bash

destfile=/etc/hosts.allow

while getopts d:f: opt; do
    case $opt in
    d)  datastore=$OPTARG
        ;;
    f)  destfile=$OPTARG
        ;;
    esac
done
(
    flock -n 9 || exit 1

    retval=0
    startts=$(date +%s%N)

    tmpdest=$(mktemp $destfile.XXXXXXXX)
    cp $destfile $tmpdest

    msg=$(datastore-fetch ${datastore}/hosts.allow/relay.mail.umich.edu $tmpdest)
    if [[ $? -eq 0 ]]; then
        diff -q $tmpdest $destfile &>/dev/null
        if [[ $? -eq 1 ]]; then
            msg='Allowed host data updated'
            oldcount=$(wc -l $destfile | awk '{print $1}')
            newcount=$(wc -l $tmpdest | awk '{print $1}')
            if [[ $oldcount -gt 100 ]] && [[ $newcount -lt $(( oldcount / 2 )) ]]; then
                msg="Too much negative skew. $tmpdest only has $newcount lines, $destfile has $oldcount."
                retval=1
            else
                msg="$destfile updated"
                mv $tmpdest $destfile
            fi
        else
            msg="$destfile unchanged"
        fi
    else
        retval=2
    fi

    rm -f $tmpdest

    duration=$(( $(date +%s%N) - startts ))

    jq -n -r \
        --arg status $retval \
        --arg duration $(( duration / 1000000000 )).$(( duration % 1000000000 / 1000000 )) \
        --arg msg "$msg" \
        '{ check: { metadata: { name: "tcpd-update", "fatigue_check/occurrences": "3" }, ttl: 3600, duration: $duration | tonumber, status: $status | tonumber, output: $msg }}' | ncat localhost 3030

    exit $retval
) 9>>/var/run/tcpd-update.lock
retval=$?

if [[ $RETURN_RC -ne 0 ]]; then
    exit $retval
fi
