#!/bin/dash
# virus scan with clamd and clamdscan

cleanup() {
    if [ -s $CLAMERR ]; then
        mv $CLAMTMP /var/tmp/
    else
        rm -rf $CLAMTMP
    fi
}

CLAMTMP=$(mktemp -d /tmp/80_clamav.XXXXXXXX)
CLAMOUT=${CLAMTMP}/output
CLAMERR=${CLAMTMP}/stderr
CLAMDSCAN=/usr/bin/clamdscan
CLAMDSCAN_FLAGS="--config-file /etc/clamd.conf --quiet --no-summary --wait -l ${CLAMOUT}"

if check_dfile; then
    # read from fast queue
    ${CLAMDSCAN} ${CLAMDSCAN_FLAGS} ${SIMTA_DFILE} 2>|${CLAMERR}
    CLAMRET=$?

    case $CLAMRET in
    0)
	cleanup
	;;

    1)  signame=$(sed -e '1d; s/.*: //; s/ FOUND$//' $CLAMOUT)
        case $signame in
            *Phish*)
                sigtype=Phishing
                ;;
            Sanesecurity.Auction*)
                sigtype=Phishing
                ;;
            Sanesecurity.Blurl*)
                sigtype=Phishing
                ;;
            Sanesecurity.Casino*)
                sigtype=Phishing
                ;;
            Sanesecurity.Test*)
                sigtype=Phishing
                ;;
            UMICH.APER*)
                sigtype=Phishing
                ;;
            *)
                sigtype=Virus
                ;;
        esac
        egrep -q 'Heuristics.Phishing.Email' $CLAMOUT
        if [ $? -eq 0 ]; then
            log "80_clamav ${SIMTA_DFILE}: $signame: $sigtype URL heuristic ignored"
            cleanup
        else
            log "80_clamav ${SIMTA_DFILE}: $signame: $sigtype rejected"
            cleanup
            echo "Rejected by local content policy"
            filter_exit ${MESSAGE_REJECT}
        fi
	;;

    2)
	log "80_clamav ${SIMTA_DFILE}: clamd error, saved in $CLAMTMP"
	cleanup
	filter_exit ${MESSAGE_TEMPFAIL}
	;;

    *)
	log "80_clamav ${SIMTA_DFILE}: $CLAMDSCAN returned $CLAMRET"
	cleanup
	filter_exit ${MESSAGE_TEMPFAIL}
	;;

    esac
fi

cleanup
