#!/bin/bash

tmpfile=$(mktemp /tmp/redis-remove.XXXXXXXX)

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <host>" >&2
    exit 1
fi

redis-cli -h $1 CLUSTER NODES > $tmpfile

myid=$(grep myself $tmpfile | awk '{print $1}')

if grep -q myself,master $tmpfile; then
    slave=$(sed -n -e "/slave $myid/{s/:.*//;s/.* //;p;q}" $tmpfile)
    echo "Promoting $slave to master"
    redis-cli -h $slave CLUSTER FAILOVER
    until grep -q myself,slave $tmpfile || [[ $try -gt 30 ]]; do
        echo "Waiting for $1 to become a slave..."
        (( try++ ))
        sleep 1
        redis-cli -h $1 CLUSTER NODES > $tmpfile
    done
fi

if grep -q myself,slave $tmpfile; then
    for rhost in $(sed -n -e 's/:.*//;s/.* //;p' $tmpfile); do
        redis-cli -h $rhost CLUSTER FORGET $myid
    done
else
    echo "$1 is not a slave, we can't remove it!" >&2
    rm -f $tmpfile
    exit 1
fi

redis-cli -h $1 CONFIG appendonly no
redis-cli -h $1 SHUTDOWN NOSAVE

rm -f $tmpfile
