#!/bin/dash

skiplist=/etc/mail/trust.rcpt

if [ -s $skiplist ] && check_tfile ; then
    match=$(jq -r .recipients[] $SIMTA_TFILE | fgrep -ixf $skiplist 2>/dev/null)
    ret=$?
    if [ $ret -eq 0 ]; then
        log "35_recipient: matched $match"
        filter_exit ${MESSAGE_ACCEPT}
    fi
fi
