#!/bin/dash

skiplist=/etc/mail/trust.rcpt

if [ -s $skiplist ] && check_tfile ; then
    match=$(jq -r .recipients[] $SIMTA_TFILE | fgrep -ixf $skiplist 2>/dev/null)
    ret=$?
    if [ $ret -eq 0 ]; then
        log "35_recipient: matched $match"
        echo "mscan.accept.recipient:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
        filter_exit ${MESSAGE_ACCEPT}
    fi
fi
