#!/bin/bash

skiplist=/etc/mail/trust.rcpt

if [ -s $skiplist ] && check_tfile ; then
    match=$(grep ^R $SIMTA_TFILE | fgrep -if $skiplist 2>/dev/null)
    ret=$?
    if [ $ret -eq 0 ]; then
        log "35_recipient: matched $match"
        filter_exit ${MESSAGE_ACCEPT}
    fi
fi
