#!/bin/dash

if check_dfile; then
    # $load1 is from 75_load
    if [ ${load1%.*} -lt 30 ]; then
        spamscore=$(spamc -c -s 1048576 <$SIMTA_DFILE 2>/dev/null)
        spamret=$?
        spamscore=${spamscore%/*}

        case $spamret in
        0)
            log "80_spamassassin: score $spamscore : pass"
            ;;
        1)
            if ! simrbl -q -l spamassassin-reject.dnsbl "$SIMTA_REMOTE_IP"; then
                log "80_spamassassin: score $spamscore : reject"
                filter_exit $MESSAGE_REJECT
            fi
            if [ ${spamscore%.*} -gt 10 ] ; then
                log "80_spamassassin: score $spamscore : reject"
                filter_exit $MESSAGE_REJECT
            fi
            log "80_spamassassin: score $spamscore : tempfail"
            filter_exit $MESSAGE_TEMPFAIL
            ;;
        *)
            log "80_spamassassin: score unknown"
            ;;
        esac
    else
        log "80_spamassassin: scan skipped, load is $load1"
    fi
fi
