#!/bin/dash

if check_dfile; then
    # $load1 is from 00_load
    if [ ${load1%.*} -lt 10 ]; then
        spamscore=$(spamc -c -s 1048576 <$SIMTA_DFILE 2>/dev/null)
        spamret=$?
	spamscore=${spamscore%/*}

        case $spamret in
        0)
            log "80_spamassassin: score $spamscore : pass"
            ;;
        1)
            if ! simrbl -q -l spamassassin-reject.dnsbl "$SIMTA_REMOTE_IP"; then
                log "80_spamassassin: score $spamscore : reject"
                filter_exit $MESSAGE_REJECT
            fi
            if [ ${spamscore%.*} -gt 10 ] ; then
                log "80_spamassassin: score $spamscore : reject"
                filter_exit $MESSAGE_REJECT
            fi
            # PENALTYBOX_PASS is from 70_pb
            if [ $PENALTYBOX_PASS -eq 1 ] ; then
                log "80_spamassassin: score $spamscore : penaltybox"
                logmsg=$($penaltybox_bin $penaltybox_args "spamassassin")
                pbret=$?
                if [ x"$logmsg" != x ]; then
                    log "80_spamassassin: $logmsg"
                fi
                if [ $pbret -eq $MESSAGE_TEMPFAIL ]; then
                    filter_exit $MESSAGE_TEMPFAIL
                fi
                PENALTYBOX_PASS=0
            else
                log "80_spamassassin: score $spamscore : noaction"
            fi
            ;;
        *)
            log "80_spamassassin: score unknown"
            ;;
        esac
    else
        log "80_spamassassin: scan skipped, load is $load1"
    fi
fi
