#!/usr/local/venv/system/bin/python3

import re
import sys

import boto3
import requests

metric_file = '/var/lib/prometheus/node_exporter/ec2_tags.prom'

reject_tags = [
    'Name',
    'CustomDNSName',
]

# Fetch the region and ID from the AWS metadata service
region = requests.get('http://169.254.169.254/latest/meta-data/placement/availability-zone').text[:-1]
iid = requests.get('http://169.254.169.254/latest/meta-data/instance-id').text

client = boto3.resource('ec2', region_name=region)
instance = client.Instance(iid)

tags = []
for tag in instance.tags:
    if tag['Key'] not in reject_tags:
        tags.append('{}="{}"'.format(tag['Key'], tag['Value']))

metrics = [
    'instance_region{{region="{}"}} 1'.format(region),
    'instance_tag{{{}}} 1'.format(','.join(tags)),
]

try:
  with open(metric_file, 'w', encoding='utf-8') as f:
    for l in metrics:
        f.write(l)
        f.write("\n")
except IOError:
    print('Failed to write metric file')
    sys.exit(1)
