#!/usr/bin/python
# Copyright 2017-2018 Rob Carleski, The University of Michigan
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF 
# ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

import urllib2, json, re, argparse, sys
import datetime, time, os

def main():

    # Grab the JSONP version of the status page from Google.
    pageData = None
    attempt = 0
    while pageData is None and attempt < 3:
        attempt += 1
        try:
            pageData = urllib2.urlopen(urllib2.Request('http://www.google.com/appsstatus/json/en'))
        except:
            pass

    if pageData is None:
        print 'Failed to fetch app status'
        sys.exit(3)

    # Build a regex object to 'convert' the returned JSONP to JSON.
    regex = re.compile("\((.+)\);$")
    search = regex.search(pageData.read())

    # The JSON is now stored in search.groups()[0].
    statusJSON = json.loads(search.groups()[0])

    # Create a dictionary of available service names
    services = {}
    for service in statusJSON['services']:
        services[service['id']] = service['name']

    retval = 0
    for message in statusJSON['messages']:
        if message['resolved'] == False:
            print "[{service}] {message}".format(service=services[message['service']], message=message['message'])
            retval = 1

    if retval == 0:
        print 'No problems reported on appstatus.google.com'

    sys.exit(retval)

if __name__ == '__main__':
    main()

