#!/usr/bin/env python

import sys
from kitchen.text.converters import getwriter
import feedparser
from html2text import html2text

# Make python's print() actually work
sys.stdout = getwriter('utf8')(sys.stdout)

ok_strings = [
    '<strong>Resolved</strong>',
    '<strong>Complete</strong>',
    'Box has resolved',
    '<strong>Monitoring</strong>',
]

retval = 0
status = feedparser.parse('https://status.box.com/history.atom')

if 'bozo_exception' in status:
    print "feedparser.parse failed"
    print status.bozo_exception
    sys.exit(3)

for entry in status.entries:
    # There's no structured indicator of status, so we hope that they stick the
    # correct string in there.
    if any(x in entry.summary for x in ok_strings):
        continue

    print html2text(entry.summary).strip()
    retval = 2

if retval == 0:
    print "No problems reported on status.box.com"

sys.exit(retval)
