#!/usr/bin/env python

import sys
import feedparser
from html2text import html2text

retval = 0
status = feedparser.parse('https://status.box.com/history.atom')

for entry in status.entries:
    # There's no structured indicator of status, so we hope that they stick the
    # correct string in there.
    if '<strong>Resolved</strong>' in entry.summary or '<strong>Complete</strong>' in entry.summary or 'Box has resolved' in entry.summary:
        continue

    print html2text(entry.summary).strip()
    retval = 2

if retval == 0:
    print "No problems reported on status.box.com"

sys.exit(retval)
