#!/bin/dash

if [ $SIMTA_DFILE] && [ $SIMTA_TFILE ]; then
    dest_domain=$(ejq -r -f $SIMTA_TFILE -e '.recipients[0]' | tr A-Z a-z)
    dest_domain=${dest_domain##*@}
    if [ "x$dest_domain" != 'xumich.edu' ] && [ "x${dest_domain#*.}" != 'xumich.edu' ]; then
        spamout=$(rspamc --json --timeout=20 $SIMTA_DFILE 2>/dev/null)

        # Use jq to format the JSON into the bits we want
        spamres=$(printf '%s' $spamout | jq -r '@text "\(.action) score=\(.score)"')
        if [ $? -ne 0 ]; then
            log "80_rspamd: bad return: $(echo $spamout | tr -d '\n')"
        fi
        spamsymbols=$(printf '%s' $spamout | jq -j '.symbols[] | del(.description) | flatten | @text')
        spamaction=${spamres% score=*}

        log "80_rspamd: $spamres symbols={$spamsymbols}"
        if [ "$spamaction" = 'reject' ]; then
            echo "mscan.bounce.rspamd:1|c" | socat -ly -t 0 STDIN UDP:localhost:8125 >/dev/null 2>&1
            echo "Forwarding forbidden by local policy"
            filter_exit $MESSAGE_BOUNCE
        fi
    fi
fi
