# outbound scanning is for connections from our own infrastructure, so there's
# no value in checking the actual EHLO or connecting host. We could try to
# re-inject the values from the original connection, but in addition to being
# effort it might not be a great idea to lie and potentially confuse Rspamd.
helo_enabled = false;
hostname_enabled = false;
