- tags:
    - falcon
    - crowdstrike
  block:
    - name: Install sensor
      ansible.builtin.dnf:
        name: falcon-sensor
        state: latest

    - name: Set sensor options
      ansible.builtin.command:
        cmd: /opt/CrowdStrike/falconctl -s -f --cloud=us-1 --cid={{ lookup('flowerysong.hvault.kv', 'crowdstrike').cid }}

    - name: Generate AID
      ansible.builtin.command:
        cmd: /opt/CrowdStrike/falconctl -g --aid

    - name: Start sensor
      ansible.builtin.systemd_service:
        name: falcon-sensor
        # can't restart, it won't work and will also break the systemd state
        state: started

    - when: "'packer' in group_names"
      block:
        - name: Unset AID
          ansible.builtin.command:
            cmd: /opt/CrowdStrike/falconctl -d -f --aid
