#!/bin/bash

name=sa-update-server
confdir=/usr/local/collaboration/dispatch

rule_dir=/var/lib/spamassassin
archive_dir=/home/spamassassin

. /usr/libexec/comint/setup

saversion=$(perl -MMail::SpamAssassin -e 'print $Mail::SpamAssassin::VERSION')
if [[ -e ${rule_dir}/$saversion ]]; then
    # If there's no update available, exit
    sa-update --update-dir $rule_dir --checkonly -v | grep -q 'Update available' || exit
fi

# Run in a subshell to capture the output
(
ruleversion=$(date +%Y%m%d%H%M)
olddir=$(readlink -f ${rule_dir}/$saversion)

sa-update --updatedir ${archive_dir}/$ruleversion
if [[ $? -ne 0 ]]; then
    echo "sa-update exited non-zero, keeping the old ruleset"
    exit 1
fi

rm -f ${rule_dir}/$saversion
mkdir -p ${rule_dir}
ln -s ${archive_dir}/$ruleversion ${rule_dir}/$saversion

sa-compile --quiet &>/dev/null

spamassassin --lint
# FIXME: handle failures?

) 2>&1 | eval $notifycmd_debug $notifywho_debug

cleanup
