#!/bin/bash

srcfile=dnsl/iia/ipv4-smtp
destfile=/etc/mail/mitn-ipv4-smtp
destset=blocklist

while getopts b:d:f:r: opt; do
    case $opt in
    b)  destset=$OPTARG
        ;;
    d)  datastore=$OPTARG
        ;;
    f)  destfile=$OPTARG
        ;;
    r)  region=$OPTARG
        ;;
    s)  srcfile=$OPTARG
        ;;
    esac
done
(
    flock -n 9 || exit 1

    retval=0
    startts=$(date +%s%N)

    if [[ ! -f $destfile ]]; then
        touch $destfile
    fi

    tmpdest=$(mktemp $destfile.XXXXXXXX)
    cp $destfile $tmpdest

    msg=$(datastore-fetch --s3-bucket ${datastore} --s3-region ${region} $srcfile $tmpdest)
    if [[ $? -eq 0 ]]; then
        diff -q $tmpdest $destfile &>/dev/null
        if [[ $? -eq 1 ]]; then
            msg='Firewall list data updated'
            oldcount=$(wc -l $destfile | awk '{print $1}')
            newcount=$(wc -l $tmpdest | awk '{print $1}')
            msg="$destfile updated (old: $oldcount, new: $newcount)"
            # FIXME: we need to be smarter about syncing the
            # list contents, but it requires dedicated logic because
            # firewalld doesn't smart.
            firewall-cmd --ipset=$destset --remove-entries-from-file=$destfile
            mv $tmpdest $destfile
            firewall-cmd --ipset=$destset --add-entries-from-file=$destfile

        else
            msg="$destfile unchanged"
        fi
    else
        retval=2
    fi

    rm -f $tmpdest

    duration=$(( $(date +%s%N) - startts ))

    jq -n -r \
        --arg status $retval \
        --arg duration $(( duration / 1000000000 )).$(( duration % 1000000000 / 1000000 )) \
        --arg msg "$msg" \
        '{ check: { metadata: { name: "fwbl-update", annotations: { "fatigue_check/occurrences": "3" }}, ttl: 3600, duration: $duration | tonumber, status: $status | tonumber, output: $msg }}' | curl -X POST -H 'Content-Type: application/json' -d @- http://127.0.0.1:3031/events

    exit $retval
) 9>>/var/run/fwbl-update.lock
retval=$?

if [[ $RETURN_RC -ne 0 ]]; then
    exit $retval
fi
