#!/usr/local/venv/system/bin/python

import argparse

import netaddr

parser = argparse.ArgumentParser()
parser.add_argument('-f', '--file', required=True)
parser.add_argument('-s', '--set', required=True)
parser.add_argument('-x', '--exclude')
args = parser.parse_args()


