#!/bin/bash

spamout=$(rspamc --json --timeout=20 --ip='127.0.0.1' --from='<greylist@example.com>' --helo='example.com' --hostname='example.com' <<EOF
Subject: Test greylist action
Message-ID: <GREYLIST.10110111@example.com>
Date: Thu, 05 Apr 2018 20:00:00 +0000
From: Grey List <greylist@example.com>, Gray List <graylist@example.com>
To: undisclosed-recipients:;
MIME-Version: 1.0

This is a test email that looks slightly suspicious.

How exciting.
EOF
2>/dev/null)

spamres=$(printf '%s' "$spamout" | jq -r '@text "\(.action) score=\(.score)"')
if [[ $? -ne 0 ]]; then
    echo "Unable to parse returned data"
    printf '%s' "$spamout"
    exit 1
fi
spamaction=${spamres% score=*}

if [[ $spamaction != 'greylist' ]]; then
    retval=2
    echo "Incorrect action returned:"
else
    retval=0
    echo "All good:"
fi
echo $spamres

exit $retval
